export const VIDEO_HISTORY_OS_DI_TOKEN = Symbol('VIDEO_HISTORY_OS_DI_TOKEN');
export const VIDEO_HISTORY_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_HISTORY_HIT_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_HISTORY_HIT_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_LAST_HISTORY_HIT_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_LAST_HISTORY_HIT_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_HISTORY_MULTIPLE_HIT_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_HISTORY_MULTIPLE_HIT_IGNITE_DI_TOKEN',
);
