export const VIDEO_HISTORY_OS_DI_TOKEN = Symbol('VIDEO_HISTORY_OS_DI_TOKEN');

export const VIDEO_HISTORY_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_IGNITE_DI_TOKEN',
);
export const GET_VIDEO_HISTORY_RANGE_DI_TOKEN = Symbol(
  'GET_VIDEO_HISTORY_RANGE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_LAST_HISTORY_HIT_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_LAST_HISTORY_HIT_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_HISTORY_MULTIPLE_HIT_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_HISTORY_MULTIPLE_HIT_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_LIST_ADAPTER_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_LIST_ADAPTER_IGNITE_DI_TOKEN',
);
export const VIDEO_HISTORY_GET_DATA_STREAM_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_GET_DATA_STREAM_DI_TOKEN',
);
