export const GET_PAGE_BY_KEYWORD_SERVICE = Symbol(
  'GET_PAGE_BY_KEYWORD_SERVICE',
);
export const GET_KEYWORD_INFO_SERVICE = Symbol('GET_KEYWORD_INFO_SERVICE');

export const GET_RELATE_WORDS_API_DI_TOKEN = Symbol(
  'GET_RELATE_WORDS_API_DI_TOKEN',
);
export const LATEST_VIDEO_HISTORY_ADAPTER: unique symbol = Symbol(
  'LATEST_VIDEO_HISTORY_ADAPTER',
);
