export enum RELWORDS_DI_TOKEN {
  FIND_ONE = 'RELWORDS_DI_TOKEN_FIND_ONE',
  FIND_ONE_BY_ELASTICACHE = 'RELWORDS_DI_TOKEN_FIND_ONE_BY_ELASTICACHE',

  FIND_ALL_BY_SQL = 'RELWORDS_DI_TOKEN_FIND_ALL',
}

export const RELATED_WORD_GET_VIDEO_HISTORY = Symbol(
  'RELATED_WORD_GET_VIDEO_HISTORY',
);
