export enum RELWORDS_DI_TOKEN {
  FIND_ONE = 'RELWORDS_DI_TOKEN_FIND_ONE',
  FIND_ONE_BY_ELASTICACHE = 'RELWORDS_DI_TOKEN_FIND_ONE_BY_ELASTICACHE',

  FIND_ALL_BY_SQL = 'RELWORDS_DI_TOKEN_FIND_ALL',
}

export const TOKEN_GET_VIDEO_HISTORY_SINGLE = Symbol(
  'TOKEN_GET_VIDEO_HISTORY_SINGLE',
);
export const RELATED_WORD_TOKEN_GET_VIDEO_HISTORY_MULTIPLE = Symbol(
  'TOKEN_GET_VIDEO_HISTORY_MULTIPLE',
);
export const CACHE_CLIENT = Symbol('CACHE_CLIENT');

export const CACHE_FIND_ALL_QUERY = Symbol('CACHE_FIND_ALL_QUERY');

export const CACHE_SET_DIC_TERM = Symbol('CACHE_SET_DIC_TERM');
