export const VIDEO_DATA_REPOSITORY_DI_TOKEN = Symbol(
  'VIDEO_DATA_REPOSITORY_DI_TOKEN',
);
export const VIDEO_HISTORY_REPOSITORY_DI_TOKEN = Symbol(
  'VIDEO_HISTORY_REPOSITORY_DI_TOKEN',
);
export const CRAWLED_VIDEO_REPOSITORY_DI_TOKEN = Symbol(
  'CRAWLED_VIDEO_REPOSITORY_DI_TOKEN',
);
