export const CHANNEL_DATA_REPOSITORY_DI_TOKEN = Symbol(
  'CHANNEL_DATA_REPOSITORY_DI_TOKEN',
);
export const CHANNEL_HISTORY_REPOSITORY_DI_TOKEN = Symbol(
  'CHANNEL_HISTORY_REPOSITORY_DI_TOKEN',
);
