export const CHANNEL_HISTORY_OS_DI_TOKEN = Symbol('CHANNEL_HISTORY_OS');
export const CHANNEL_HISTORY_IGNITE_DI_TOKEN = Symbol(
  'CHANNEL_HISTORY_IGNITE_DI_TOKEN',
);
export const CHANNEL_HISTORY_LATEST_TUPLE_IGNITE_DI_TOKEN = Symbol(
  'CHANNEL_HISTORY_LATEST_TUPLE_IGNITE_DI_TOKEN',
);
export const CHANNEL_HISTORY_GET_RELATE_VIDEO_IGNITE_DI_TOKEN = Symbol(
  'CHANNEL_HISTORY_GET_RELATE_VIDEO_IGNITE_DI_TOKEN',
);

export const CHANNEL_HISTORY_BY_CHANNEL_ID_IGNITE_DI_TOKEN = Symbol(
  'CHANNEL_HISTORY_BY_CHANNEL_ID_IGNITE_DI_TOKEN',
);
