export const CHANNEL_DATA_REPOSITORY = Symbol('CHANNEL_DATA_REPOSITORY');

export const CHANNEL_TERM = Symbol('CHANNEL_TERM');

export const CHANNEL_DATA_REPOSITORY_BY_OS = Symbol(
  'CHANNEL_DATA_REPOSITORY_BY_OS',
);
