export const POST_REQUEST_CHANNEL_SERVICE_TOKEN = Symbol(
  'POST_REQUEST_CHANNEL_SERVICE_TOKEN',
);
export const REQUEST_CHANNEL_REPOSITORY_DI_TOKEN = Symbol(
  'REQUEST_CHANNEL_REPOSITORY_DI_TOKEN',
);
