export enum VIDEO_DI_TOKEN {
  FIND_BY_VIDEO_ID = 'VIDEO_DI_TOKEN_FIND_BY_VIDEO_ID',
  ATHENA_FIND_BY_VIDEO_ID = 'ATHENA_VIDEO_DI_TOKEN_FIND_BY_VIDEO_ID',
  FIND_VIDEO_DATA_REPOSITORY_BY_OS = 'OS_VIDEO_DI_TOKEN_FIND_BY_KEYWORD_TAG',
}
