export const VIDEO_OS_DI_TOKEN = Symbol('VIDEO_OS_DI_TOKEN');

export const VIDEO_IGNITE_DI_TOKEN = Symbol('VIDEO_IGNITE_DI_TOKEN');

export const VIDEO_SERVICE_DI_TOKEN = Symbol('VIDEO_SERVICE_DI_TOKEN');
