export const clustersCategories: Record<string, string> = {
  0: '뉴스',
  1: '제작/DIY',
  2: '드라마',
  3: '가족/일상',
  4: '해외뉴스',
  5: '교육>역사',
  6: '푸드>먹방',
  7: '메타버스',
  8: '종교',
  9: '농사',
  10: '기타',
  11: '사업',
  12: '교육>영어',
  13: '부동산',
  14: '주식/투자',
  15: '정치',
  16: '낚시',
  17: '사연/라디오',
  18: '자동차',
  19: '골프',
  20: '동물>반려견',
  21: '악기',
  22: '여행',
  23: '콘서트',
  24: '부동산',
  25: '교육',
  26: '축구',
  27: '스포츠',
  28: '트로트',
  29: '코인',
  30: '건강>병원',
  31: '재즈',
  32: '운세/사주',
  33: '뉴스',
  34: '푸드>베이킹',
  35: '애니메이션',
  36: '뷰티',
  37: '글로벌',
  38: '패션',
  39: '음악',
  40: '토토',
  41: '동물>고양이',
  42: '만화',
  43: '게임>리그오브레전드',
  44: '키즈',
  45: '종교>불교',
  46: '인터넷방송>버튜버',
  47: '전쟁>무기',
  48: '요리',
  49: '자동차',
  50: '전쟁>러시아',
  51: '건강>피트니스',
  52: '아이돌',
  53: '종교>기독교',
  54: '게임>발로란트',
  55: '연애',
  56: '자기계발',
  57: '교육>수학',
  58: '게임>리니지',
  59: '게임>포켓몬',
  60: '코미디',
  61: '인터넷방송>스트리머',
  62: '공포',
  63: '댄스',
  64: '영화',
  65: 'IT/태크',
  66: '캠핑',
  67: '백색소음',
  68: '게임>모바일',
  69: '기타',
  70: '힐링',
  71: '주식',
} as const;

export const clustersCategoriesOptions: { value: number; label: string }[] = [
  { value: 0, label: '뉴스' },
  { value: 1, label: '제작/DIY' },
  { value: 2, label: '드라마' },
  { value: 3, label: '가족/일상' },
  { value: 4, label: '해외뉴스' },
  { value: 5, label: '교육>역사' },
  { value: 6, label: '푸드>먹방' },
  { value: 7, label: '메타버스' },
  { value: 8, label: '종교' },
  { value: 9, label: '농사' },
  { value: 10, label: '기타' },
  { value: 11, label: '사업' },
  { value: 12, label: '교육>영어' },
  { value: 13, label: '부동산' },
  { value: 14, label: '주식/투자' },
  { value: 15, label: '정치' },
  { value: 16, label: '낚시' },
  { value: 17, label: '사연/라디오' },
  { value: 18, label: '자동차' },
  { value: 19, label: '골프' },
  { value: 20, label: '동물>반려견' },
  { value: 21, label: '악기' },
  { value: 22, label: '여행' },
  { value: 23, label: '콘서트' },
  { value: 24, label: '부동산' },
  { value: 25, label: '교육' },
  { value: 26, label: '축구' },
  { value: 27, label: '스포츠' },
  { value: 28, label: '트로트' },
  { value: 29, label: '코인' },
  { value: 30, label: '건강>병원' },
  { value: 31, label: '재즈' },
  { value: 32, label: '운세/사주' },
  { value: 33, label: '뉴스' },
  { value: 34, label: '푸드>베이킹' },
  { value: 35, label: '애니메이션' },
  { value: 36, label: '뷰티' },
  { value: 37, label: '글로벌' },
  { value: 38, label: '패션' },
  { value: 39, label: '음악' },
  { value: 40, label: '토토' },
  { value: 41, label: '동물>고양이' },
  { value: 42, label: '만화' },
  { value: 43, label: '게임>리그오브레전드' },
  { value: 44, label: '키즈' },
  { value: 45, label: '종교>불교' },
  { value: 46, label: '인터넷방송>버튜버' },
  { value: 47, label: '전쟁>무기' },
  { value: 48, label: '요리' },
  { value: 49, label: '자동차' },
  { value: 50, label: '전쟁>러시아' },
  { value: 51, label: '건강>피트니스' },
  { value: 52, label: '아이돌' },
  { value: 53, label: '종교>기독교' },
  { value: 54, label: '게임>발로란트' },
  { value: 55, label: '연애' },
  { value: 56, label: '자기계발' },
  { value: 57, label: '교육>수학' },
  { value: 58, label: '게임>리니지' },
  { value: 59, label: '게임>포켓몬' },
  { value: 60, label: '코미디' },
  { value: 61, label: '인터넷방송>스트리머' },
  { value: 62, label: '공포' },
  { value: 63, label: '댄스' },
  { value: 64, label: '영화' },
  { value: 65, label: 'IT/태크' },
  { value: 66, label: '캠핑' },
  { value: 67, label: '백색소음' },
  { value: 68, label: '게임>모바일' },
  { value: 69, label: '기타' },
  { value: 70, label: '힐링' },
  { value: 71, label: '주식' },
];
