export const CHANNEL_REPOSITORY = Symbol('CHANNEL_REPOSITORY');
export const CHANNEL_DATA_DI_TOKEN = Symbol('CHANNEL_DATA_DI_TOKEN');
export const CHANNEL_DATA_LIST_DI_TOKEN = Symbol('CHANNEL_DATA_LIST_DI_TOKEN');
export const CHANNEL_INFO_ADAPTER_DI_TOKEN = Symbol(
  'CHANNEL_INFO_ADAPTER_DI_TOKEN',
);
export const AUTO_CHANNEL_NAME_DI_TOKEN = Symbol('AUTO_CHANNEL_NAME_DI_TOKEN');
export const TIME_LINE_TOKEN_DI_TOKEN = Symbol('TIME_LINE_TOKEN_DI_TOKEN');
export const CHANNEL_REGISTRATION = Symbol('CHANNEL_REGISTRATION');
