export const CHANNEL_REPOSITORY = Symbol('CHANNEL_REPOSITORY');
export const CHANNEL_DATA_DI_TOKEN = Symbol('CHANNEL_DATA_DI_TOKEN');
export const CHANNEL_DATA_LIST_DI_TOKEN = Symbol('CHANNEL_DATA_LIST_DI_TOKEN');
export const CHANNEL_INFO_ADAPTER_DI_TOKEN = Symbol(
  'CHANNEL_INFO_ADAPTER_DI_TOKEN',
);
