export function generateDummyData(count) {
  const getRandomInt = (min, max) =>
    Math.floor(Math.random() * (max - min + 1)) + min;
  const channelHistories = [];

  for (let i = 0; i < count; i++) {
    const year = 2024;
    // 1월부터 12월까지 무작위로 생성
    const month = getRandomInt(1, 1);
    // 각 달의 일수를 고려하지 않고 1일부터 28일까지로 단순화
    const day = getRandomInt(1, 10);
    // 채널 평균 조회수와 비디오 조회수를 무작위로 생성
    const channelAverageViews = getRandomInt(100, 1000);
    const videoViews = getRandomInt(50, 1500);

    channelHistories.push({
      channelAverageViews,
      videoViews,
      year,
      month,
      day,
    });
  }

  return channelHistories;
}
export const calculateDailyPerformanceDummy = [
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 1,
  },
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2590,
    year: 2024,
    month: 1,
    day: 2,
  },
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2591,
    year: 2024,
    month: 1,
    day: 3,
  },
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2592,
    year: 2024,
    month: 1,
    day: 4,
  },
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2593,
    year: 2024,
    month: 1,
    day: 5,
  },
  {
    videoId: 'SZH-l0J6yUo',
    videoViews: 498,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2594,
    year: 2024,
    month: 1,
    day: 6,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 1,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 2,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 3,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 4,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 5,
  },
  {
    videoId: 'MiUPeUk32M4',
    videoViews: 2209,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 6,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 1,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 2,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 3,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 4,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 5,
  },
  {
    videoId: 'B7y_TH8p6GI',
    videoViews: 314,
    channelId: 'UClXxSPTQwzkROBssIMh9Pjg',
    channelAverageViews: 455,
    year: 2024,
    month: 1,
    day: 6,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 1,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 2,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 3,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 4,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 5,
  },
  {
    videoId: 'po-b6w0WJHM',
    videoViews: 12084,
    channelId: 'UCTPu77GGFTV2gWpAuK8f7Cg',
    channelAverageViews: 14349,
    year: 2024,
    month: 1,
    day: 6,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 1,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 2,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 3,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 4,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 5,
  },
  {
    videoId: 'ufFfK1gI8h0',
    videoViews: 529,
    channelId: 'UClfnwyDy1janeAYc4Pssk8g',
    channelAverageViews: 2585,
    year: 2024,
    month: 1,
    day: 6,
  },
];
