export enum DAILY_VIEWS_DI_TOKEN {
  FIND = 'DAILY_VIEWS_DI_TOKEN_FIND',
}

export enum DAILY_VIEWS_DI_TOKEN_ATHENA {
  FIND_QUERY = 'DAILY_VIEWS_DI_TOKEN_FIND_QUERY',
}
export const WEEKLY_VIEWS_REPOSITORY = Symbol('WEEKLY_VIEWS_REPOSITORY');
export const WEEKLY_VIEWS_SERVICE_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_SERVICE_DI_TOKEN',
);

export const WEEKLY_VIEWS_REPOSITORY_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_DI_TOKEN',
);
