import { CalculateDailyHitsMetricsService } from '@Apps/modules/hits/application/services/calculate-daily-hits.service';

export const WEEKLY_VIEWS_SERVICE_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_SERVICE_DI_TOKEN',
);
export const WEEKLY_VIEWS_SERVICE_V2_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_SERVICE_V2_DI_TOKEN',
);

export const WEEKLY_VIEWS_REPOSITORY_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_DI_TOKEN',
);

export const EXPECTED_HITS_SERVICE_DI_TOKEN = Symbol(
  'EXPECTED_HITS_SERVICE_DI_TOKEN',
);

export const HITS_VIDEO_CHANNEL_HISTORY_IGNITE_DI_TOKEN = Symbol(
  'HITS_VIDEO_CHANNEL_HISTORY_IGNITE_DI_TOKEN',
);

export const DAILY_HITS_METRICS_SERVICE_IGNITE_DI_TOKEN = Symbol(
  'DAILY_HITS_METRICS_SERVICE_IGNITE_DI_TOKEN',
);
export const WEEKLY_VIEWS_REPOSITORY_V2_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_V2_DI_TOKEN',
);
