export const WEEKLY_VIEWS_SOME_SERVICE_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_SOME_SERVICE_DI_TOKEN',
);
export const WEEKLY_VIEWS_SERVICE_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_SERVICE_DI_TOKEN',
);

export const WEEKLY_VIEWS_REPOSITORY_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_DI_TOKEN',
);

export const DAILY_HITS_METRICS_SERVICE_IGNITE_DI_TOKEN = Symbol(
  'DAILY_HITS_METRICS_SERVICE_IGNITE_DI_TOKEN',
);
export const DAILY_HITS_SERVICE_DI_TOKEN = Symbol(
  'DAILY_HITS_SERVICE_DI_TOKEN',
);
export const WEEKLY_VIEWS_REPOSITORY_V2_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_V2_DI_TOKEN',
);
export const WEEKLY_VIEWS_REPOSITORY_V1_DI_TOKEN = Symbol(
  'WEEKLY_VIEWS_REPOSITORY_V1_DI_TOKEN',
);
export const PROBABILITY_SUCCESS_SERVICE_DI_TOKEN = Symbol(
  'PROBABILITY_SUCCESS_SERVICE_DI_TOKEN',
);

export const VIDEO_CHANNEL_AVERG_VIEWS_BY_DATE_KEYWORD_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_CHANNEL_AVERG_VIEWS_BY_DATE_KEYWORD_IGNITE_DI_TOKEN',
);
export const VIDEO_VIEWS_BY_DATE_KEYWORD_IGNITE_DI_TOKEN = Symbol(
  'VIDEO_VIEWS_BY_DATE_KEYWORD_IGNITE_DI_TOKEN',
);

export const ANALYSIS_HITS_SERVICE_DI_TOKEN = Symbol(
  'ANALYSIS_HITS_SERVICE_DI_TOKEN',
);
export const ANALYSIS_HITS_V2_SERVICE_DI_TOKEN = Symbol(
  'ANALYSIS_HITS_V2_SERVICE_DI_TOKEN',
);
export const GET_WEEKLY_KEYWORD_SERVICE_DI_TOKEN = Symbol(
  'GET_WEEKLY_KEYWORD_SERVICE_DI_TOKEN',
);
